title: Home
author: Molly Liu
email: liberare@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal site for Molly Liu
# social links
twitter_username: mozliu
github_username: mozliu

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
